logging:
  level:
    io:
      seata: error
server:
  port: 9093
spring:
  application:
    name: account-service
  cloud:
    alibaba:
      seata:
        tx-service-group: account-service-group
    nacos:
      discovery:
        server-addr: 192.168.0.132:8848
        namespace: 386e230f-13dd-4fde-9c34-4d0e01383b98
        group: SEATA_GROUP
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.132:3306/seata_account?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
seata:
  registry:
    type: nacos
    nacos:
      server-addr: 192.168.0.132:8848
      group: SEATA_GROUP
      namespace: 386e230f-13dd-4fde-9c34-4d0e01383b98
      username: nacos
      password: nacos
  config:
    type: nacos
    nacos:
      server-addr: 192.168.0.132:8848
      group: SEATA_GROUP
      namespace: 386e230f-13dd-4fde-9c34-4d0e01383b98
      username: nacos
      password: nacos